### ISSUE TITLE
Force close on playing movies

### ISSUE THREAD

**Issue by Meshkati** [kazemnejad/televisak-issue-tracker#1]
موقع پخش فیلم یا تریلر ها فورس کلوز میشه
Device: OnePlus One
OS: CyanogenMod Nightly 12.1 ( Android 5.1.1 )

**Comment by kazemnejad** [comment]
what is your app version?

**Comment by Meshkati** [comment]
0.1

**Comment by kazemnejad** [comment]
مچکر
با کامیت شماره 
`098fdfa3ccab05b2e8f654c06dded5b4f7cd31b7`
فیکس شد.
