### ISSUE TITLE
Profile picture preview problem

### ISSUE THREAD

**Issue by Meshkati** [kazemnejad/televisak-issue-tracker#2]
موقع انتخاب پروفایل پیکچر برای اولین بار، قسمت پیش نمایش همچنان بک گراند آبی رو نشون میده. حتی با زدن تیک بالای صفحه و مشاهده ی اسنک بار با پیام « با موفقیت به روز شد » همچنان پیش نمایش آبی هست
این مساله فقط برای اولین انتخاب پروفایل پیکچر اتفاق میافته و برای دفعات بعدی پیش نمایش درست نمایش داده میشه
Device:OnePlus one
OS: CyanogenMod Nightly 12.1 ( Android 5.1.1 )
App version: 0.1.2

**Comment by kazemnejad** [comment]
با تشکر

با کامیت شماره
`33dbce99cb5ee45e1fccd294f5e49a111463d0e9`
و 
`1a7c82c8e2485e65885969fbd2d9d7ec60ff61db`
فیکس شد.

**Comment by kazemnejad** [comment]
نسخه جدید رو هم تو قسمت دانلود گذاشتیم:)
